[project]
name = "homedepot"
version = "0.1.0"
description = "Backend for Home Depot's"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.135.1",
    "fastapi-users[sqlalchemy]>=15.0.4",
    "pwdlib[argon2]",
    "pydantic[email]>=2.12.5",
    "pyjwt",
    "python-dotenv>=1.2.2",
    "tzdata>=2026.2",
    "uvicorn>=0.41.0",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pylance>=7.0.0",
]

[project.scripts]
serve = "main:main"
